server:
  port: ${APPLICATION_PORT:8000}

spring:
  application:
    name: authorization-server
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:root}
      database: ${MONGODB_DATABASE:application}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}